services:
  server:
    build:
      context: ./server  # Set correct path
      dockerfile: Dockerfile # Use correct Dockerfile name
    ports:
      - "8080:8080"  # Expose backend API
    volumes:
      - ./server:/server  # Ensure correct mounting
    environment:
      - PYTHONPATH=/server
